# 网站基础设置
title: Zhao62的博客
description: 专注 AI 与深度学习的研究笔记
author: Zhao62

# 启用 Beautiful Jekyll 主题
remote_theme: daattali/beautiful-jekyll

# 必须的插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# 主题美化设置
beautiful-jekyll:
  title-page: true # 允许单独的标题页
  visual-page: true
